sudo: false
language: ruby
cache: bundler
matrix:
  include:
  - rvm: jruby-9.1.13.0
    env: LOGSTASH_BRANCH=master
  - rvm: jruby-9.1.13.0
    env: LOGSTASH_BRANCH=7.0
  - rvm: jruby-9.1.13.0
    env: LOGSTASH_BRANCH=6.7
  - rvm: jruby-9.1.13.0
    env: LOGSTASH_BRANCH=6.6
  fast_finish: true
install: true
script: ci/build.sh
jdk: oraclejdk8
deploy:
  provider: rubygems
  api_key: $rubygems_api_key
  on:
    tags: true
